RECORD_STATES_FOLDER = 'record_states'
FILES_STATES_FOLDER = 'file_states'

# TRANSFORMATOR

LOADER_CANONICAL_FORMATTER = 7000
ERROR_LOADER_CANONICAL_FORMATTER = 7001
DB_UPSERT = 8000
ERROR__DB_UPSERT = 8001